# Development environment configuration

spring:
  # Database configuration - Local PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/mcb_db
    username: mcb_user
    password: mcb_password
    driver-class-name: org.postgresql.Driver
    hikari:
      # Connection pool configuration
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      pool-name: McbHikariCP-Dev
      
  # Flyway database migration configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
    
  # JPA/Hibernate configuration (if needed)
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# JWT configuration
jwt:
  secret: mcb-dev-jwt-secret-key-change-in-production-environment
  expiration: 86400000 # 24 hours in milliseconds

# Security configuration
security:
  # Allowed CORS origins for development environment
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:3001

# Development-specific configuration
dev:
  # Enable development tools
  debug: true
  # Enable SQL logging
  sql-logging: true

# Actuator - expose more endpoints in development environment
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always